apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicegateway.fullname" . }}
  labels:
{{ include "servicegateway.labels" . | indent 4 }}
data:
  servicegateway.json: |
    {{ .Values.servicegateway.config.content | toJson }}
  {{- if .Values.additionalConfigmapData }}
    {{- toYaml .Values.additionalConfigmapData | nindent 2}}
  {{- end }}